### ISSUE TITLE
Minimum required numpy version needs to be bumped to 1.17.0

### ISSUE THREAD

**Issue by shakhat** [RaRe-Technologies/gensim#3137]
#### Problem description

gensim is declared to work with numpy >= 1.11.3, however it doesn't work with any version below 1.17.0.

#### Steps/code/corpus to reproduce

Install gensim and non-recent version of numpy:

```bash
$ pip install "numpy<1.17.0" gensim
```

Run python interpreter with the following code
```python
>>> import gensim
```

Observed error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/.venv/lib/python3.7/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
  File "/private/tmp/.venv/lib/python3.7/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/private/tmp/.venv/lib/python3.7/site-packages/gensim/parsing/preprocessing.py", line 26, in <module>
    from gensim import utils
  File "/private/tmp/.venv/lib/python3.7/site-packages/gensim/utils.py", line 62, in <module>
    default_prng = np.random.default_rng()
AttributeError: module 'numpy.random' has no attribute 'default_rng'
```

The solution is to bump the minimum version of numpy to be at least 1.17.0: https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L318

#### Versions

```
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.6
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.6.3
```

**Comment by mpenkov** [comment]
I think this is the discussion here: https://github.com/RaRe-Technologies/gensim/issues/3085

We did it for gensim-wheels, but not for gensim proper. It's a slightly different problem. I think we can bump the minimum version to 1.17.0 as mentioned in this ticket.

**Comment by piskvorky** [comment]
Fixed in #3156.
