### PR TITLE
Fix backward compatibility issue: loading `FastTextKeyedVectors` using `KeyedVectors` (missing attribute `compatible_hash`)

### LINKED ISSUE #2341: fastText  fixes in 3.7 break compatibility with old models
Recent fixes to Gensim's fastText implementation introduced in #2313 are great. Unfortunately, they also break compatibility with fastText models trained by older Gensim versions - if the models are stored as a KeyedVectors() object. One can load such a model, but as soon as you try to do anything useful (like `most_similar()`, etc), it fails, because the `compatible_hash` attribute is missing.
If this attribute is added manually after the loading, everything goes fine.

#### Steps/Code/Corpus to Reproduce
```
import gensim

model = gensim.models.KeyedVectors.load(ANY_KEYED_VECTORS_FASTTEXT_MODEL)
model.most_similar(positive=ANY_WORD)
```
#### Expected Results
The `compatible_hash` attribute is automatically assigned the False value on load, and the model works as before.

#### Actual Results
```
/usr/local/lib/python3.5/dist-packages/gensim/models/keyedvectors.py in word_vec(self, word, use_norm)
   2057 
   2058         """
-> 2059         hash_fn = _ft_hash if self.compatible_hash else _ft_hash_broken
   2060 
   2061         if word in self.vocab:

AttributeError: 'FastTextKeyedVectors' object has no attribute 'compatible_hash'

```

#### Versions
Linux-4.15.0-43-generic-x86_64-with-LinuxMint-18.3-sylvia
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
NumPy 1.14.5
SciPy 1.1.0
gensim 3.7.0
FAST_VERSION 1

### PR DESCRIPTION
**Pull request by menshikh-iv**
Fix #2341 

CC: @akutuzov, if you have a time, can you check, is current PR fix your problem (I already added an test, just to be fully sure)?

### CODE REVIEW

**Comment by akutuzov** [comment]
@menshikh-iv yes it does.

**Comment by anotherbugmaster** [comment]
@akutuzov, @mpenkov, @piskvorky

I'm afraid it's still broken, guys.

Here's an example:

```
In [1]: from gensim.models.keyedvectors import FastTextKeyedVectors                                    

In [2]: fasttext = FastTextKeyedVectors.load('araneum_none_fasttextcbow_300_5_2018.model')             

In [3]: fasttext['всё сломалось']
/usr/local/bin/ipython3:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed
in 4.0.0, use self.wv.__getitem__() instead).
  #!/usr/bin/python3
---------------------------------------------------------------------------                            
AttributeError                            Traceback (most recent call last)                            
<ipython-input-3-d748222dd7f0> in <module>
----> 1 fasttext['всё сломалось']

~/.local/lib/python3.6/site-packages/gensim/utils.py in new_func1(*args, **kwargs)                     
   1445                     stacklevel=2
   1446                 )
-> 1447                 return func(*args, **kwargs)
   1448
   1449             return new_func1

~/.local/lib/python3.6/site-packages/gensim/models/fasttext.py in __getitem__(self, words)             
    926
    927         """
--> 928         return self.wv.__getitem__(words)
    929
    930     @deprecated("Method will be removed in 4.0.0, use self.wv.__contains__() instead")         

~/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py in __getitem__(self, entities)      
    345         if isinstance(entities, string_types):                                                 
    346             # allow calls like trained_model['office'], as a shorthand for trained_model[['offi$e']]
--> 347             return self.get_vector(entities)
    348
    349         return vstack([self.get_vector(entity) for entity in entities])                        

~/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py in get_vector(self, word)           
    463
    464     def get_vector(self, word):
--> 465         return self.word_vec(word)
    466
    467     def words_closer_than(self, w1, w2):

~/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py in word_vec(self, word, use_norm)
   2089                 ngram_weights = self.vectors_ngrams
   2090             ngrams_found = 0
-> 2091             for ngram_hash in ft_ngram_hashes(word, self.min_n, self.max_n, self.bucket, self.co
mpatible_hash):
   2092                 if ngram_hash in self.hash2index:
   2093                     word_vec += ngram_weights[self.hash2index[ngram_hash]]

AttributeError: 'FastTextKeyedVectors' object has no attribute 'compatible_hash'
```
