### ISSUE TITLE
gensim 4.4.0 - pypi sdist fails to compile on python 3.12

### ISSUE THREAD

**Issue by chargr** [RaRe-Technologies/gensim#3634]
upstream sdist for 4.4.0 contains files generated with older cython resulting in build failure on python 3.12
and the file fastss.pyx to generate fastss.c is missing in the sdist.  
attempting to delete generated files and regenerate fails.

```
ff7865acb98f: gensim/models/word2vec_inner.c: In function ‘__Pyx_PyInt_As_PY_LONG_LONG’:
ff7865acb98f: gensim/models/word2vec_inner.c:12812:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
ff7865acb98f: 12812 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
ff7865acb98f: |                                                     ^~
ff7865acb98f: gensim/models/word2vec_inner.c:12867:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
ff7865acb98f: 12867 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
ff7865acb98f: |                                                     ^~
ff7865acb98f: gensim/models/word2vec_inner.c: In function ‘__Pyx_PyInt_As_int’:
ff7865acb98f: gensim/models/word2vec_inner.c:13046:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
ff7865acb98f: 13046 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
ff7865acb98f: |                                                     ^~
ff7865acb98f: gensim/models/word2vec_inner.c:13101:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
ff7865acb98f: 13101 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
ff7865acb98f: |                                                     ^~
ff7865acb98f: gensim/models/word2vec_inner.c: In function ‘__Pyx_PyInt_As_unsigned_PY_LONG_LONG’:
ff7865acb98f: gensim/models/word2vec_inner.c:13242:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
ff7865acb98f: 13242 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
ff7865acb98f: |                                                     ^~
```

```
$ head gensim-4.4.0/gensim/models/word2vec_inner.c
/* Generated by Cython 0.29.32 */

/* BEGIN: Cython Metadata
{
    "distutils": {
        "depends": [
            "gensim/models/voidptr.h"
        ],q
        "include_dirs": [
            "gensim/models"

```

```
$ diff -ur gensim gensim-4.4.0
Only in gensim: CITATION.cff
Only in gensim: config.sh
Only in gensim: continuous_integration
Only in gensim: CONTRIBUTING.md
Only in gensim: docs
Only in gensim-4.4.0/gensim/corpora: _mmreader.c
Only in gensim/gensim: examples
Only in gensim-4.4.0/gensim: _matutils.c
Only in gensim-4.4.0/gensim/models: doc2vec_corpusfile.cpp
Only in gensim-4.4.0/gensim/models: doc2vec_inner.cpp
Only in gensim-4.4.0/gensim/models: fasttext_corpusfile.cpp
Only in gensim-4.4.0/gensim/models: fasttext_inner.c
Only in gensim-4.4.0/gensim/models: nmf_pgd.c
Only in gensim-4.4.0/gensim/models: word2vec_corpusfile.cpp
Only in gensim-4.4.0/gensim/models: word2vec_inner.c
Only in gensim-4.4.0/gensim/similarities: fastss.c
Only in gensim/gensim/similarities: fastss.pyx
Only in gensim-4.4.0: gensim.egg-info
Only in gensim: 'gensim Quick Start.ipynb'
Only in gensim: .git
Only in gensim: .github
Only in gensim: .gitignore
Only in gensim: HACKTOBERFEST.md
Only in gensim: ISSUE_TEMPLATE.md
Only in gensim: pip.sh
Only in gensim-4.4.0: PKG-INFO
Only in gensim: release
Only in gensim: requirements_docs.txt
Only in gensim: SECURITY.md
diff -ur gensim/setup.cfg gensim-4.4.0/setup.cfg
--- gensim/setup.cfg    2025-10-28 14:37:35.494129000 -0700
+++ gensim-4.4.0/setup.cfg      2025-10-17 18:24:41.564885900 -0700
@@ -1,6 +1,8 @@
 [wheelhouse_uploader]
-artifact_indexes=
-    #
-    # See https://github.com/RaRe-Technologies/gensim/wiki/Developer-page
-    #
-    http://gensim-wheels.s3-website-us-east-1.amazonaws.com/
+artifact_indexes =
+       http://gensim-wheels.s3-website-us-east-1.amazonaws.com/
+
+[egg_info]
+tag_build =
+tag_date = 0
+
```

**Comment by julianpollmann** [comment]
@chargr Which platform do you use?

**Comment by chargr** [comment]
linux.  I am using the `quay.io/pypa/manylinux2014_x86_64` image to make a 2014/2.17 wheel

**Comment by chargr** [comment]
my build steps look something like this:

```
pip install oldest-supported-numpy
pip wheel -v --no-build-isolation --no-deps -w dist/ .
```

running setup.py build_ext produces the same

clean_ext causes failure because of the missing file:
```
running clean_ext
removing gensim/_matutils.c
removing gensim/similarities/fastss.c
removing gensim/corpora/_mmreader.c
removing gensim/models/doc2vec_corpusfile.cpp
removing gensim/models/fasttext_inner.c
removing gensim/models/word2vec_corpusfile.cpp
removing gensim/models/fasttext_corpusfile.cpp
removing gensim/models/doc2vec_inner.cpp
removing gensim/models/nmf_pgd.c
removing gensim/models/word2vec_inner.c
/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
toml section missing PosixPath('pyproject.toml') does not contain a tool.setuptools_scm section
running build_ext
Traceback (most recent call last):
  File "/tmp/python.KYLnc/gensim-4.4.0/setup.py", line 335, in <module>
    setup(
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/__init__.py", line 115, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
    self.run_command(cmd)
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/dist.py", line 1102, in run_command
    super().run_command(command)
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1020, in run_command
    cmd_obj.ensure_finalized()
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 135, in ensure_finalized
    self.finalize_options()
  File "/tmp/python.KYLnc/gensim-4.4.0/setup.py", line 123, in finalize_options
    Cython.Build.cythonize(list(make_c_ext(use_cython=True)), language_level=3)
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 978, in cythonize
    module_list, module_metadata = create_extension_list(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 809, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python.KYLnc/module-build/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 80, in nonempty
    raise ValueError(error_msg)
ValueError: 'gensim/similarities/fastss.pyx' doesn't match any files
```
