### ISSUE TITLE
module 'gensim.models.doc2vec' has no attribute 'FAST_VERSION'

### ISSUE THREAD

**Issue by ecorro** [RaRe-Technologies/gensim#2827]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0]
NumPy 1.18.4
SciPy 1.4.1
gensim 3.8.3
AttributeError: module 'gensim.models.doc2vec' has no attribute 'FAST_VERSION'

The issue is that the FAST_VERSION attribute is not there anymore in this new version. All works well in Gensim 3.8.1

**Comment by piskvorky** [comment]
Cannot replicate. It is very fishy that **word2vec**.FAST_VERSION returns an error for a different class, gensim.models.**doc2vec** has no attribute 'FAST_VERSION'.

Are you sure you're running the code shown?

**Comment by ecorro** [comment]
Yes, I'm sure, I actually used Jupyter's attribute browser to verify manually and the FAST_VERSION attribute was not there. I removed Gensim and other pacakges from that virtual env (all generated with conda) and I can't reproduce the output not. I'll try to reproduce the setup this evening and will share the setup steps to provide the whoe detail. Thanks.

**Comment by ecorro** [comment]
I just gave it another try with a new environment and could not reproduce the problem either. I'm not sure what happened in the first place. So all good and sorry for the inconvenience. T
